name: ScreenshotApp

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  ScreenshotApp:
    type: application
    platform: macOS
    sources:
      - path: ScreenshotApp
        excludes:
          - "*.plist"
    info:
      path: ScreenshotApp/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: Screenshot
        NSScreenCaptureUsageDescription: "スクリーンショットを撮影するためにアクセスが必要です"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.screenshotapp
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_APP_SANDBOX: NO
        PRODUCT_NAME: ScreenshotApp
